[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "webkit-test"
version = "0.1.0"

[dependencies]
gtk = "^0.6"
webkit2gtk = "^0.6"

[dependencies.relm]
default-features = false
path = "../.."

[dependencies.relm-derive]
path = "../../relm-derive"
