[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["development-tools::testing", "gui"]
description = "Testing library for relm"
documentation = "https://docs.rs/relm-test/"
license = "MIT"
name = "relm-test"
repository = "https://github.com/antoyo/relm"
version = "0.21.0"
edition = "2018"

[dependencies]
enigo = "^0.0.14"
gdk = "^0.13.0"
glib = "^0.10.0"
gtk = "^0.9.0"
gtk-test = "^0.6"

[dependencies.relm]
path = ".."
version = "^0.21.0"
